### PR TITLE
[hotfix] git add check was missing

### PR DESCRIPTION
**Pull request by 404answernotfound**
fix(git-wrapper missing git add handler): added case where user did not git add

git add check was missing

### CODE REVIEW

**Comment by 404answernotfound** [comment]
not yet ready

**Comment by TheJoin95** [comment]
I was thinking on an different approach, more like this one: https://github.com/mcwhittemore/staged-git-files

Showing the files that are ready to be committed and eventually commit. We should find out which one is the best

**Comment by 404answernotfound** [comment]
Would you like it better to also try and apply "adds" from within the script, having the user choose which files to add or * directly, based on choice?

edit: we should go for "git add *", having a selection of files could lead to the terminal showing quite a few files and folders if user didn't do any git add after the git init

**Comment by TheJoin95** [comment]
Can you please close this PR? I should have resolved with the latest commits using https://git-scm.com/docs/git-status#Documentation/git-status.txt---porcelainltversiongt

**Pull request closed without merging**
